#!/usr/bin/env python3
import os
import hmac
import hashlib
import requests

my_path = os.path.abspath(os.path.dirname(__file__))
secretKeyPath = os.path.join(my_path, "../secretKey")
dataLogPath = os.path.join(my_path, "data.log")

with open(secretKeyPath, 'r') as keyfile:
    secretKey = keyfile.read().strip()

digest_maker = hmac.new(secretKey.encode('utf-8'), b'', hashlib.sha256)

with open(dataLogPath, 'r') as datafile:
    body = datafile.read()
mode = "overwrite"
digest_maker.update((mode + body).encode('utf-8'))
signature = digest_maker.hexdigest()

url = 'http://localhost:8080/updateQueueData' #Update this with the relevant domain
headers = {'content-type': 'application/json', 'signature': signature}
r = requests.post(url, json={"data_str": body, "mode": mode}, headers=headers)
print(r)
