#!/usr/bin/env python3
import os
import hmac
import socket
import struct
import hashlib
import requests

def ntpTimestamp(addr='0.de.pool.ntp.org'):
    REF_TIME_1970 = 2208988800 # Reference time
    client = socket.socket( socket.AF_INET, socket.SOCK_DGRAM )
    data = '\x1b' + 47 * '\0'
    client.sendto(data.encode(), (addr, 123))
    data, _ = client.recvfrom(1024)
    if data:
        t = struct.unpack( '!12I', data )[10]
    t -= REF_TIME_1970
    return t

if __name__ == "__main__":
    try:
        my_path = os.path.abspath(os.path.dirname(__file__))
        secretKeyPath = os.path.join(my_path, "../secretKey")
        dataLogPath = os.path.join(my_path, "data.log")

        with open(secretKeyPath, 'r') as keyfile:
            secretKey = keyfile.read().strip()

        with open(dataLogPath, 'r') as datafile:
            queue_data = datafile.read()

        mode      = "overwrite"
        timestamp = int(round(ntpTimestamp()))

        digest_maker = hmac.new(secretKey.encode('utf-8'), b'', hashlib.sha256)
        digest_maker.update((str(timestamp) + mode + queue_data).encode('utf-8'))
        signature = digest_maker.hexdigest()

        url = 'http://localhost:8080/updateQueueData' #Update this with the relevant domain
        headers = {'content-type': 'application/json', 'signature': signature}
        r = requests.post(url, json={"data_str": queue_data, "mode": mode, "timestamp": timestamp}, headers=headers)
        print("Sent with response:")
        print(r)
    except:
        print("Failed to send")
